CREATE TABLE IF NOT EXISTS products (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    title VARCHAR(255),
    price DECIMAL(19,2),
    handle VARCHAR(255) NOT NULL UNIQUE,
    vendor VARCHAR(255),
    image CLOB
);
